[package]
name = "rime"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["cargo"] }
crossterm = "0.27.0"
libc = "0.2.154"
ratatui = "0.26.2"
uuid = { version = "1.8.0", features = ["rng", "v1"] }
